language: php

addons:
  chrome: stable

sudo: false

php: [7.1, 7.2, 7.3]

matrix:
  allow_failures:
      - env: DEPENDENCIES='dev'
  fast_finish: true
  include:
      # Test against dev versions of dependencies
    - php: 7.3
      env: DEPENDENCIES='dev'

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - if [ "$DEPENDENCIES" = "dev" ]; then composer config minimum-stability dev; fi;

install:
  - composer install -n
  # Start a webserver for web fixtures.
  - vendor/bin/mink-test-server > /dev/null 2>&1 &

script: vendor/bin/phpunit -v --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_failure:
  - cat /tmp/webdriver_output.txt
